### ISSUE TITLE
Optimization application

### ISSUE THREAD

**Issue by Lubyvyi** [rubykube/barong#501]
At the moment, when I pass verification after each step, I need to make an additional request to update the user state.
for example,I registered and my initial level is 1. then I passed the phone number verification and my level changed to the second (on the backend) but on the frontend it is still first. And in order for the frontend to be in sync with the backend, I need to make an update request user (I think this is an extra request).
my suggestion: when I make a request to phone verification, for example, in the response send me an updated user (if the request is successfully processed)
It also helps to solve the problem number 500. for example, I sent a passport for verification and in response to me comes an updated user with some flag that will mean that the passport is uploaded but it is waiting for verification at the moment

**Comment by maksim-litvinov** [comment]
You can use `renew` endpoint https://github.com/rubykube/barong/blob/master/docs/index.md#postv1securityrenew

**Comment by vadym-poberezhny** [comment]
**Renew** endpoint kind of relates to authentification, we use it to update jwt token.
Possible to put information about level into  **profiles/me** endpoint. Using it would be more convenient since we need to check level
- after each step and verify if user can go further or not.
- when user come back to site after a while and has level (with pending value) - need to check if it's updated.

**Comment by maksim-litvinov** [comment]
We have level at `accounts/me` endpoint https://github.com/rubykube/barong/blob/master/app/api/user_api/v1/accounts.rb#L11
