### ISSUE TITLE
404 Error on api /v1/profiles/me when user's profile not found

### ISSUE THREAD

**Issue by ElviraMiro** [rubykube/barong#534]
Now, when GET /v1/profiles/me and user's profile does not exist Barong send http status: 404
Can change to http status: 204?

**Comment by maksim-litvinov** [comment]
204 is not correct code for that purpose

**Comment by Lubyvyi** [comment]
from the side of the backend - yes, but not from the frontend. We catch all errors in the requests (404 is an error) and notify the user of these errors. In my opinion, in this case, the absence of the profile should not be a mistake for the frontend, because the request was successful and just the profile = null

**Comment by yivo** [comment]
Maxim is correct, don't make shit of HTTP, 404 is for non-existing things.

**Comment by maksim-litvinov** [comment]
Backend can respond with empty json
